name: thrifters_united
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  vertical_tabs:
  google_fonts:
  auto_size_text:
  cached_network_image:
  pin_code_fields: ^7.3.0
  font_awesome_flutter:
  geolocator:
  intl:
  page_transition:
  timeago:
  url_launcher:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  provider:
  google_sign_in:
  flutter_facebook_auth:
  smooth_page_indicator:
  flutter_polyline_points:
  google_maps_flutter:
  country_code_picker: ^2.0.2
  geocoding:
  location:
  http:
  permission_handler:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.2.0

  flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#f7f7f7"


flutter_native_splash:
  color: "#f7f7f7"
  image: assets/thrifter.png
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Style Script
      fonts:
        - asset: assets/StyleScript-Regular.ttf

  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/


