import 'package:thrifters_classes/thrifters_classes.dart';

List<Brand> brands = names.map((e) => Brand(name: e)).toList();
List<Size> sizes = sizesNames.map((e) => Size(name: e)).toList();
List<String> names = [
  'Academie',
  'adidas',
  'adidas Originals',
  'Aeropostale',
  'Ajmal',
  'Aldo',
  'Alpha Industries',
  'American Eagle',
  'Amwaaj',
  'Another Influence',
  'Antonio Banderas',
  'Apivita',
  'Apothecary 87',
  'Aramis',
  'Armani Exchange',
  'Asics',
  'Austin Reed',
  'Aveda',
  'Avene',
  'Azzaro',
  'Babel',
  'Baldessarini',
  'Baleno',
  'Banana Republic',
  'Barber Club',
  'Barbour',
  'Barbour International',
  'Basicxx',
  'Baxter of California',
  'Being Human',
  'Ben Sherman',
  'Benetton',
  'Beverly Hills Polo Club',
  'Blood Brother',
  'Blue Age',
  'Bond Street',
  'Bossini',
  'Boucheron',
  'Brave Soul',
  'Bread and Boxers',
  'Brooks Brothers',
  'Buckley London',
  'Bvlgari',
  'Call It Spring',
  'Calvin Klein',
  'Calvin Klein Jeans',
  'CALVIN KLEIN JEANS PLUS',
  'Calvin Klein Performance',
  'Camelbak',
  'Campus Sutra',
  'Canali',
  'Casio',
  'CAT',
  'Cayler & Sons',
  'Celio',
  'Cerruti 1881',
  'Champion',
  'Christian Audigier',
  'Clarins',
  'Clarks',
  'Classics 77',
  'Clean',
  'Clinique',
  'Coach',
  'Coega',
  'Cole Haan',
  'Columbia',
  'Comme Des Garcons',
  'Continental',
  'Converse',
  'Cortefiel',
  'Cotton On',
  'Crep protect',
  'Criminal Damage',
  'Crocs',
  'Cruiser',
  'Cuba',
  'Damensch',
  'Daniel Wellington',
  'Daniel Hechter',
  'David Beckham',
  'Davidoff',
  'Dawson Sports',
  'Dedicated',
  'Defacto',
  'Demeter',
  'Diesel',
  'Difuzed',
  'Ducati Corse',
  'Dune London',
  'Dunhill',
  'EA7 Emporio Armani',
  'Eastpak',
  'Ecco',
  'Ella Bache',
  'Ellesse',
  'Emporio Armani',
  'Entente',
  'Escentric molecules',
  'fabindia',
  'Fabric Flavours',
  'Fastrack',
  'Ferrari',
  'Ferre Milano',
  'Fifteen Minutes',
  'Fila',
  'Fitbit',
  'FitFlop',
  'Fossil',
  'Fox Smith London',
  'Fred Hayman',
  'Fred Perry',
  'French Connection',
  'FRWD',
  'GANT',
  'Gc',
  'GCDS',
  'Gentlemens Tonic',
  'Geoffrey Beene',
  'Goorin Bros',
  'Goutal (Annick Goutal)',
  'Grimey',
  'Guess',
  'Hackett',
  'Hanes',
  'Happy Socks',
  'Havaianas',
  'Hawkins & Brimble',
  'Herschel Supply Co.',
  'Hoka',
  'Hollister',
  'HOOG',
  'HRX by Hrithik Roshan',
  'HUF',
  'Hugo Boss',
  'Hummel',
  'Hummer',
  'Hush Puppies',
  'HXTN Supply',
  'Iceberg',
  'Icon Brand',
  'Iconic',
  'IKKS',
  'Indosole',
  'Instafab',
  'Instafab Plus',
  'iTOUCH',
  'Izzue',
  'J.B4',
  'Jack Black',
  'Jack & Jones',
  'Jason Markk',
  'JAYXKEY',
  'Jean Paul Gaultier',
  'Jeepers & Peepers',
  'Jesus Del Pozo',
  'Jimmy Choo',
  'Jockey',
  'John Hatter',
  'John Varvatos',
  'Kanon',
  'Kappa',
  'Karl Kani',
  'Karl Keller',
  'Karl Lagerfeld',
  'Kenneth Cole',
  'Kipling',
  'Koton',
  'Krizia',
  'L\'Occitane',
  'Lab Series',
  'Label.M',
  'Lacoste',
  'Laura Biagiotti',
  'Lauren Ralph Lauren',
  'Le Confort',
  'Lee Cooper',
  'Levi\'s®',
  'Limitato',
  'Liverpool FC',
  'Liz Claiborne',
  'OREAL MEN EXPERT',
  'Loris Azzaro',
  'Lyle & Scott',
  'MANGO',
  'Mango MAN',
  'Marshall Artist',
  'Marvel',
  'Maserati',
  'Maskie',
  'Mast & Harbour',
  'MCM',
  'Mennace',
  'Mercedes Benz',
  'Michael Kors',
  'mihyar',
  'Miller Harris',
  'Minimum',
  'Missoni',
  'Mister Tee',
  'Mitchell & Ness',
  'Mont Blanc',
  'Movado',
  'MPL Sports',
  'Mugler',
  'Muji',
  'Musium Div.',
  'MVMT',
  'Namshi_Coca-Cola',
  'Namshi x Hana & Moha',
  'Napapijri',
  'Nasomatto',
  'Nautica',
  'New Balance',
  'New Era',
  'New Look',
  'Nicce',
  'Nikben',
  'Nike',
  'Nixon',
  'Nordgreen',
  'The North Face',
  'Nuxe',
  'Oakley',
  'Obaku',
  'OBEY',
  'On Running',
  'Onitsuka Tiger',
  'Only & Sons',
  'Original Penguin',
  'Outerstuff',
  'Paco Rabanne',
  'Pascal Morabito',
  'Paul Sebastian',
  'Paul Smith',
  'Payot',
  'Perry Ellis',
  'Pevonia Botanica',
  'Police',
  'Polo',
  'Polo Ralph Lauren',
  'Produkt',
  'Profound Aesthetic',
  'PS Paul Smith',
  'Pull & Bear',
  'Puma',
  'Rado',
  'Rastaclat',
  'Ray-Ban',
  'R&B',
  'Red Tape',
  'REDKEN',
  'REDKEN BREWS',
  'Reebok',
  'Reiss',
  'Rip Curl',
  'Rip N Dip',
  'Rituals',
  'River Island',
  'Robert Wood',
  'Roberto Cavalli',
  'RVCA',
  'Ryoko',
  'S.T. Dupont',
  'Sacoor Brothers',
  'SAINT HONORE PARIS',
  'Salvatore Ferragamo',
  'Salvatore Ferragamo',
  'Scotch & Soda',
  'Scuderia Ferrari',
  'Selected Homme',
  'Selfie',
  'Semir',
  'Seventy Five',
  'Shoexpress',
  'SikSilk',
  'Skagen',
  'Skechers',
  'Sneaker Lab',
  'Sothys',
  'Soulland',
  'South Beach',
  'SP Characters',
  'Spiral',
  'Springfield',
  'Spykar',
  'Squatwolf',
  'St Dupont',
  'Stance',
  'Steve Madden',
  'Styli',
  'Superdry',
  'Supply & Demand',
  'Suunto',
  'Swatch',
  'Tabac',
  'Tamashee',
  'Ted Baker',
  'The Art of Shaving',
  'The Gold Gods',
  'The House Of Oud',
  'The Hundreds',
  'The Piccadilly Shaving Co.',
  'Timberland',
  'Tissot',
  'Titan',
  'T.M.Lewin',
  'Tokyo Laundry',
  'Tom Franks',
  'Tommy Hilfiger',
  'Tommy Hilfiger Sport',
  'Tommy Jeans',
  'TOMS',
  'Tonino Lamborghini',
  'Tory Burch',
  'TOUS',
  'Trendyol',
  'Trussardi',
  'Trussardi',
  'Turtle Feet Company',
  'Typo',
  'U.S. Polo Assn.',
  'UCLA',
  'Umbro',
  'Under Armour',
  'Vans',
  'Versace',
  'Versace',
  'Victorinox',
  'Vince Camuto',
  'Vital',
  'Vogue',
  'Warner Bros.',
  'Wild For The Weekend',
  'Wrogn',
  'Zoggs',
  '11 degrees',
  '4711',
  '87ORIGINS'
];
List<String> sizesNames = [
  '12',
  '14',
  '18',
  '20',
  '22',
  '22-24',
  '25-27',
  '26',
  '26X30',
  '26X32',
  '27X30',
  '27X32',
  '28',
  '28-30',
  '28X30',
  '28X32',
  '28X34',
  '29',
  '29X30',
  '29X32',
  '29X34',
  '2XL',
  '2XS',
  '30',
  '30X30',
  '30X32',
  '30X34',
  '31',
  '31-33',
  '31X30',
  '31X32',
  '31X34',
  '31X36',
  '32',
  '32X30',
  '32X32',
  '32X34',
  '32X36',
  '33',
  '33X30',
  '33X32',
  '33X34',
  '34',
  '34-36',
  '34-38',
  '34X30',
  '34X32',
  '34X34',
  '34X36',
  '35',
  '35-37',
  '35-38',
  '35X30',
  '35X32',
  '35X34',
  '36',
  '36-39',
  '36-40',
  '36R',
  '36X30',
  '36X32',
  '36X34',
  '36X36',
  '37',
  '37-39',
  '38',
  '38-42',
  '38R',
  '38X30',
  '38X32',
  '38X34',
  '38X36',
  '39',
  '39-42',
  '3XL',
  '40',
  '40-42',
  '40R',
  '40X32',
  '40X34',
  '41',
  '41-46',
  '42',
  '42-46',
  '42R',
  '42X32',
  '42X34',
  '43',
  '43-45',
  '43-46',
  '43-47',
  '44',
  '44R',
  '44X32',
  '44X34',
  '45',
  '46',
  '46R',
  '46X32',
  '46X34',
  '48',
  '48R',
  '48X32',
  '48X34',
  '4XL',
  '50',
  '52',
  '52R',
  '54',
  '56',
  '58',
  '5XL',
  '60',
  '6XL',
  '7-11',
  '7XL',
  '8',
  'L',
  'L/XL',
  'M',
  'M/L',
  'OS',
  'S',
  'S/M',
  'XL',
  'XS',
  'XS/S',
  'XXS',
];
